<html>  
    <head>  
        <title>sondage</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
		
    </head>  
    <body>  
	<header></header>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li <?php if(@$_GET['q']==1) echo'class="active"'; ?>><a href="welcome.php?q=1"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;Home<span class="sr-only">(current)</span></a></li>
                    <li <?php if(@$_GET['q']==2) echo'class="active"'; ?>> <a href="welcome.php?q=2"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp;History</a></li>
                    <li <?php if(@$_GET['q']==3) echo'class="active"'; ?>> <a href="welcome.php?q=3"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span>&nbsp;Ranking</a></li>
                    <li <?php if(@$_GET['q']==4) echo'class="active"'; ?>> <a href="admin.php?q=4"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp;Créer son quizz</a></li>
                    <li <?php if(@$_GET['q']==5) echo'class="active"'; ?>> <a href="tchat.php?q=5"><span class="glyphicon glyphicon-check" aria-hidden="true"></span>&nbsp;Résultats/Tchat</a></li>
                    <li <?php if(@$_GET['q']==5) echo'class="active"'; ?>> <a href="index2.php?q=6"><span class="glyphicon glyphicon-check" aria-hidden="true"></span>&nbsp;Sondage</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
        <div class="container">  
            <br />  
            <br />
			<br />

			<div class="row">
				<div class="col-md-6">
						
					<form method="post" id="poll_form">
					<h1>Le titre du sondage est: <?= $_GET['sondage'] ?></h2> 
					<br>
					<h2>La question du sondage est: <?= $_GET['question'] ?></h2> 
						<br />
					
						<div class="radio">
							<label><h4><input type="radio" name="poll_option" class="poll_option" value="Laravel"/> <?= $_GET["choix1"]; ?>
							</h4></label>
						</div>
						
						<div class="radio">
							<label><h4><input type="radio" name="poll_option" class="poll_option" value="CodeIgniter"/> <?=  $_GET["choix2"]; ?> </h4></label>
						</div>
						<div class="radio">
							<label><h4><input type="radio" name="poll_option" class="poll_option" value="CakePHP"/>  <?=  $_GET["choix3"]; ?></h4></label>
						</div>
						<div class="radio">
							<label><h4><input type="radio" name="poll_option" class="poll_option" value="Phalcon"/>  <?=  $_GET["choix4"]; ?></h4></label>
						</div>
						<div class="radio">
							<label><h4><input type="radio" name="poll_option" class="poll_option" value="Symfony" />  <?= $_GET["choix5"]; ?></h4></label>
						</div>
						<br />
					
						<input type="submit" name="poll_button" id="poll_button" class="btn btn-primary" />
					</form>

					<br />
				</div>
				<div class="col-md-6">
					<br />
					<br />
					<br />
					<h4>Résultats du sondage</h4><br />
					<div id="poll_result"></div>
				</div>
			</div>
		
			
			<br />
			<br />
			<br />
		</div>
    </body>  
</html>  
<script>  
$(document).ready(function(){
	
	fetch_poll_data();

	function fetch_poll_data()
	{
		$.ajax({
			url:"fetch_poll_data.php",
			method:"POST",
			success:function(data)
			{
				$('#poll_result').html(data);
			}
		});
	}
	
	$('#poll_form').on('submit', function(event){
		event.preventDefault();
		var poll_option = '';
		$('.poll_option').each(function(){
			if($(this).prop("checked"))
			{
				poll_option = $(this).val();
			}
		});
		if(poll_option != '')
		{
			$('#poll_button').attr('disabled', 'disabled');
			var form_data = $(this).serialize();
			$.ajax({
				url:"poll.php",
				method:"POST",
				data:form_data,
				success:function()
				{
					$('#poll_form')[0].reset();
					$('#poll_button').attr('disabled', false);
					fetch_poll_data();
					alert("Poll Submitted Successfully");
				}
			});
		}
		else
		{
			alert("Please Select Option");
		}
	});
	
	
	
});  
</script>